config/routes.rb
Rails.application.routes.draw do
  root 'home_page#index'
  get '/pull_requests',    to: 'pull_requests#index'
  get '/pulse',            to: 'insights#pulse'
  get '/contributors',     to: 'insights#contributors'
  get '/community',        to: 'insights#community'
  get '/traffic',          to: 'insights#traffic'
  get '/commits',          to: 'insights#commits'
  get '/code_frequency',   to: 'insights#code_frequency'
  get '/dependency_graph', to: 'insights#dependency_graph'
  get '/network',          to: 'insights#network'
  get '/forks',            to: 'insights#forks'
  get '/signup',           to: 'users#new'
  post 'signup',           to: 'users#create'
  get '/profile',          to: 'users#profile'
  get '/login',            to: 'sessions#new'
  post '/login',           to: 'sessions#create'
  delete '/logout',        to: 'sessions#destroy'
  get '/issues',           to: 'issues#show'
  get '/edit',             to: 'users#edit'
  get '/activate',         to: 'account_activations#activate'
  get '/new',              to: 'repositories#new'
  post '/new',             to: 'repositories#create'
  get '/index',            to: 'repositories#index'
  resources :repositories
  resources :users
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/controllers/insights_controller.rb
class InsightsController < ApplicationController
  def show
  end

  def pulse
  end

  def contributors
  end

  def community
  end

  def traffic
  end

  def commits
  end

  def code_frequency
  end

  def dependency_graph
  end

  def network
  end

  def forks
  end
end

app/views/insights/_menu.html.erb
<nav class="menu" data-pjax>
  <%= link_to "Pulse", pulse_path, class: "js-selected-navigation-item selected menu-item", role: "tab" %>
  <%= link_to "Contributors", contributors_path, class: "js-selected-navigation-item selected menu-item", role: "tab" %>
  <%= link_to "Community", community_path, class: "js-selected-navigation-item selected menu-item", role: "tab" %>
  <%= link_to "Traffic", traffic_path, class: "js-selected-navigation-item selected menu-item", role: "tab" %>
  <%= link_to "Commits", commits_path, class: "js-selected-navigation-item selected menu-item", role: "tab" %>
  <%= link_to "Code frequency", code_frequency_path, class: "js-selected-navigation-item selected menu-item", role: "tab" %>
  <%= link_to "Dependency graph", dependency_graph_path, class: "js-selected-navigation-item selected menu-item", role: "tab" %>
  <%= link_to "Network", network_path, class: "js-selected-navigation-item selected menu-item", role: "tab" %>
  <%= link_to "Forks", forks_path, class: "js-selected-navigation-item selected menu-item", role: "tab" %>
</nav>

app/views/insights/code_frequency.html.erb
<%= render partial: 'layouts/repo_heading' %>
<div class="container new-discussion-timeline experiment-repo-nav">
  <div class="repository-content">
    <div class="columns">
      <div class="column one-fourth">
        <%= render partial: 'insights/menu' %>
      </div>
      <div class="column three-fourth">
        <div class="graphs wheader">
          <h2 class="ghead">
            <span class="dir">
              <span class="cadd">Additions</span>
              and
              <span class="cdel">Deletions</span>
              per week
            </span>
          </h2>
          Information graph about code frequency
          <div class="js-graph graph-canvas" data-graph-name="code-frequency" data-url="#">
            <div class="activity">
              <img class="graph-loading dots" src="#" width="64" alt>
              <div class="graph-loading msg">
                <p>Crunching the latest data, just for you. Hang tight...</p>
              </div>
              <div class="graph-empty msg mt-6">
                <h4>We don`t have enough data to show anything useful.</h4>
                <p>It usually takes about a week to populate this graph</p>
              </div>
              <div class="graph-no-usable-data msg mt-6">
                <p>We need at least one non-empty commit with an email to generate this graph.</p>
              </div>
            </div>
            <div class="graph-error flash flash-error mt-6">
              <p>We tried out best, but the graph wouldn`t load. Try reloading the page.</p>
            </div>
            <svg width="730" height="500" class="viz code-frequency">
              <g transform="translate(40,10)"></g>
            </svg>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/insights/commits.html.erb
<%= render partial: 'layouts/repo_heading' %>
<div class="container new-discussion-timeline experiment-repo-nav">
  <div class="repository-content">
    <div class="columns">
      <div class="column one-fourth">
        <%= render partial: 'insights/menu'%>
      </div>
      <div class="column three-fourth">
        <div class="graphs">
          <section class="js-graph graph-canvas commit-activity-graphs" data-graph-name="commit-activity"
                   data-url="#">
            <div class="activity">
              <img class="graph-loading dots" src="#" width="64" alt>
            </div>
            <div class="graph-error flash flash-error mt-6">
              <p>We tried our best, but the gaph wouldn`t load. Try reload the page.</p>
            </div>
            <section id="commit-activity-master" class="commit-activity=master mb-6" style="width: 730px;">
              <svg width="780" height="140" class="viz">
                <g transform="translate(30,10)"></g>
              </svg>
              <p>Commits info graph 1</p>
            </section>
            <section id="commit-activity-detail">
              <svg width="740" height="320" class="viz">
                <g transform="translate"></g>
              </svg>
              <p>Commits info graph 2</p>
            </section>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/insights/community.html.erb
<%= render partial: 'layouts/repo_heading' %>
<div class="container new-discussion-timeline experiment-repo-nav">
  <div class="repository-content">
    <div class="columns">
      <div class="column one-fourth">
        <%= render partial: 'insights/menu' %>
      </div>
      <div class="column three-fourth">
        <div class="Subhead">
          <h2 class="Subhead-heading">Community profile</h2>
        </div>
        <div class="community-checklist mt-4">
          <div class="text-center my-5">
            <p class="f3-light">Here`s how this project compares to <a href="https://opensource.guide">recommended community standards</a>.</p>
          </div>
          <div class="mb-4">
            <p class="mb-2">
              <span class="f4 text-bold">Checklist</span>
            </p>
            <ul class="Box">
              <li class="bg-gray d-block border-buttom">
                <div class="progress-bar-small progress-bar-rounded-0 anim-grow-x">
                  <span class="progress" style="width: 0%">&nbsp</span>
                </div>
              </li>
              <li class="Box-row d-flex flex-wrap flex-items-baseline">
                <div class="flex-auto">
                  <svg aria-label="Added" class="octicon octicon-check mr-1 text-green" height="16"
                  role="img" verions="1.1" viewBox="0 0 12 16"
                  width="12">
                    <path fill-rule="evenodd" d="M12 51-8 8-4-4 1.5-1.5L4 1016.5-6.5z"></path>
                  </svg>
                  Description
                </div>
              </li>
              <li class="Box-row d-flex flex-wrap flex-items-baseline">
                <div class="flex-auto">
                  <svg aria-label="Added" class="octicon octicon-check mr-1 text-green" height="16"
                       role="img" verions="1.1" viewBox="0 0 12 16"
                       width="12">
                    <path fill-rule="evenodd" d="M12 51-8 8-4-4 1.5-1.5L4 1016.5-6.5z"></path>
                  </svg>
                  <a href="#" class="readme-link">
                  README
                  </a>
                </div>
              </li>
              <li class="Box-row d-flex flex-wrap flex-items-baseline">
                <div class="flex-auto">
                  <svg aria-label="Added" class="octicon octicon-check mr-1 text-green" height="16"
                       role="img" verions="1.1" viewBox="0 0 12 16"
                       width="12">
                    <path fill-rule="evenodd" d="M12 51-8 8-4-4 1.5-1.5L4 1016.5-6.5z"></path>
                  </svg>
                  <a href="#" class="code-of-conduct-link">
                  Code of conduct
                  </a>
                </div>
              </li>
              <li class="Box-row d-flex flex-wrap flex-items-baseline">
                <div class="flex-auto">
                  <svg aria-label="Added" class="octicon octicon-check mr-1 text-green" height="16"
                       role="img" verions="1.1" viewBox="0 0 12 16"
                       width="12">
                    <path fill-rule="evenodd" d="M12 51-8 8-4-4 1.5-1.5L4 1016.5-6.5z"></path>
                  </svg>
                  <a href="#" class="contribution-link">
                  Contributing
                  </a>
                </div>
              </li>
              <li class="Box-row d-flex flex-wrap flex-items-baseline">
                <div class="flex-auto">
                  <svg aria-label="Added" class="octicon octicon-check mr-1 text-green" height="16"
                       role="img" verions="1.1" viewBox="0 0 12 16"
                       width="12">
                    <path fill-rule="evenodd" d="M12 51-8 8-4-4 1.5-1.5L4 1016.5-6.5z"></path>
                  </svg>
                  <a href="#" class="license-link">
                  License
                  </a>
                </div>
              </li>
              <li class="Box-row d-flex flex-wrap flex-items-baseline">
                <div class="flex-auto">
                  <svg aria-label="Added" class="octicon octicon-check mr-1 text-green" height="16"
                       role="img" verions="1.1" viewBox="0 0 12 16"
                       width="12">
                    <path fill-rule="evenodd" d="M12 51-8 8-4-4 1.5-1.5L4 1016.5-6.5z"></path>
                  </svg>
                  <a href="#">Issue template </a>
                  and
                  <a href="#"> pull request template </a>
                </div>
              </li>
            </ul>
          </div>
          <p class="mb-4 text-small float-right">
            What is <a href="https://help.github.com/articles/viewing-your-community-profile">the community profile</a>?
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/insights/contributors.html.erb
<%= render partial: 'layouts/repo_heading' %>
<div class="container new-discussion-timeline experiment-repo-nav">
  <div class="repository-content">
    <div class="columns">
      <div class="column one-fourth">
        <%= render partial: 'insights/menu' %>
      </div>
      <div class="column three-fourth">
        <div class="graph-filter clearfix __web-inspector-hide-shortcut__">
          <div class="Subhead">
            <h2 class="Subhead-heading js-date-range">"Date" of first contribution - Current "Date"</h2>
            <div class="Subhead-actions">
              <div class="select-menu js-menu-container js-select-menu js-contribution-container">
                <button class="btn btn-sm select-menu-button js-menu-target" type="button" aria-haspopup="true" aria-expanded="false">
                  <i>Contributions</i>
                  <span class="js-select-button">Commits</span>
                </button>
                <div class="select-menu-model-holder js-menu-container js-navigation-container">
                  <div class="select-menu-model">
                    <div class="select-menu-header">
                      <svg aria-label="Close" class="octicon octicon-x js-menu-close" height="16" role="img" version="1.1"
                           viewBox="0 0 12 16" width="12"></svg>
                      <span class="select-menu-title">Filter contributions</span>
                    </div>
                    <div class="select-menu-list">
                      <div class="select-menu-item js-navigation-item">
                        <input id="ctype a" name="ctype" type="radio" value="a">
                        <svg aria-hidden="true" class="octicon octicon-check select-menu-item-icon" height="16"
                             version="1.1" viewBox="0 0 12 16" width="12"></svg>
                      </div>
                      <div class="select-menu-item js-navigation-item">
                        <input id="ctype d" name="ctype" type="radio" value="d">
                        <svg aria-hidden="true" class="octicon octicon-check select-menu-item-icon" height="16"
                             version="1.1" viewBox="0 0 12 16" width="12"></svg>
                      </div>
                      <div class="select-menu-item js-navigation-item">
                        <input id="ctype c" name="ctype" type="radio" value="c">
                        <svg aria-hidden="true" class="octicon octicon-check select-menu-item-icon" height="16"
                             version="1.1" viewBox="0 0 12 16" width="12"></svg>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <p class="info">Contributions to staging, excluding merge commits</p>
        </div>
        <div class="graphs">
          <div id="contributors-master" class="tint-box">
            <svg height="175" width="730" class="viz">
              <g transform="translate(50,20)"></g>
            </svg>
          </div>
          <div id="contributors" class="clearfix js-graph graph-canvas" data-graph-name="contributors"
               data-graph-width="335" data-url="#">
            <div class="activity">
              <img class="graph-loading dots" src="#" width="64" alt>
              <div class="graph-loading msg">
                <p>Crunching the latest data, just for you, Hang tight...</p>
              </div>
              <div class="graph-empty msg mt-6">
                <h4> We don`t have enough data to who anything useful.</h4>
                <p>It usually takes about a week to populate this graph.</p>
              </div>
              <div class="graph-no-usable-data msg mt-6">
                <p>We need at least one non-empty commit with an email to generate this graph.</p>
              </div>
            </div>
            <div class="graph-error flash flash-error mt-6">
              <p>We tried our best, but the graph wouldn`t load.Try reload the page</p>
            </div>
            <ol class="contrib-data list-style-none">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/insights/dependency_graph.html.erb
<%= render partial: 'layouts/repo_heading' %>
<div class="container new-discussion-timeline experiment-repo-nav">
  <div class="repository-content">
    <div class="columns">
      <div class="column one-fourth">
        <%= render partial: 'insights/menu' %>
      </div>
      <div class="column three-fourth">
        <div id="dependencies">
          <div class="Subhead">
            <h2 class="Subhead-heading">Dependency graph</h2>
          </div>
          <div class="tabnav">
            <nav class="tabnav-tabs" aria-label="Dependency graph menu">
              <a href="#" class="js-selected-navigation-item selected tabnav-tab"
                 data-selected-links="#" role="tab">Dependencies</a>
              <a href="#" class="js-selected-navigation-item tabnav-tab"
                 data-selected-links="#" role="tab">Dependents</a>
            </nav>
          </div>
          <div class="mb-4">
            These dependencies have been defined in <strong>GitClub</strong>`s manifest files, such as
            <a href="#" class="text-bold">FILE</a>
            and
            <a href="#" class="text-bold">FILE</a>
          </div>
          <div class="Box mb-3">
            <div class="Box-header clearfix border-buttom-0">
              <div class="table-list-filters">
                <div class="table-list-header-toggle states float-left pl-0 text-gray-dark">
                  <svg aria-hidden="true" class="octicon octicon-package mr-2 text-gray-light"
                       height="16" version="1.1" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M 1 4.27 v 7.47 c 0 0.45 0.3 0.84 0.75 0.97 l
                    6.5 1.73 c 0.16 0.05 0.34 0.05 0.5 0 l 6.5 -1.73 c 0.45 -0.13 0.75 -0.52 0.75
                    -0.97 V 4.27 c 0 -0.45 -0.3 -0.84 -0.75 -0.97 l -6.5 -1.74 a 1.4 1.4 0 0 0 -0.5
                    0 L 1.75 3.3 c -0.45 0.13 -0.75 0.52 -0.75 0.97 Z m 7 9.09 l -6 -1.59 V 5 l 6
                    1.61 v 6.75 Z M 2 4 l 2.5 -0.67 L 11 5.06 l -2.5 0.67 L 2 4 Z m 13 7.77 l -6 1.59
                    V 6.61 l 2 -0.55 V 8.5 l 2 -0.53 V 5.53 L 15 5 v 6.77 Z m -2 -7.24 L 6.5 2.8 l 2
                    -0.53 L 15 4 l -2 0.53 Z"></path>
                  </svg>
                  Dependencies defined in
                  <a href="#" class="link-gray-dark text-bold" data-octo-click="dep_graph_manifest">FILE</a>
                  <span class="Counter v-align-middle">0</span>
                </div>
              </div>
            </div>
          </div>
          <div class="Box mb-3">
            <div class="Box-header clearfix border-bottom-0">
              <div class="table-list-filters">
                <div class="table-list-header-toggle states float-left pl-0 text-gray-dark">
                  <svg aria-hidden="true" class="octicon octicon-package mr-2 text-gray-light"
                       height="16" version="1.1" viewBox="0 0 16 16" width="16">
                    <path fill-rule="evenodd" d="M 1 4.27 v 7.47 c 0 0.45 0.3 0.84 0.75 0.97 l
                    6.5 1.73 c 0.16 0.05 0.34 0.05 0.5 0 l 6.5 -1.73 c 0.45 -0.13 0.75 -0.52 0.75
                    -0.97 V 4.27 c 0 -0.45 -0.3 -0.84 -0.75 -0.97 l -6.5 -1.74 a 1.4 1.4 0 0 0 -0.5
                    0 L 1.75 3.3 c -0.45 0.13 -0.75 0.52 -0.75 0.97 Z m 7 9.09 l -6 -1.59 V 5 l 6
                    1.61 v 6.75 Z M 2 4 l 2.5 -0.67 L 11 5.06 l -2.5 0.67 L 2 4 Z m 13 7.77 l -6 1.59
                    V 6.61 l 2 -0.55 V 8.5 l 2 -0.53 V 5.53 L 15 5 v 6.77 Z m -2 -7.24 L 6.5 2.8 l 2
                    -0.53 L 15 4 l -2 0.53 Z"></path>
                  </svg>
                  Dependencies defined in
                  <a href="#" class="link-gray-dark text-bold" data-octo-click="dep_graph_manifest">FILE</a>
                  <span class="Counter v-aligin-middle">0</span>
                </div>
              </div>
            </div>
            <div class="border-top Details js-details-container">
              <div class="Box-row d-flex flex-items-center js-dependency">
                <button type="button" class="btn-link no-underline js-sub-dependencies js-details-target"
                        data-octo-click="dep_graph_package_expand" data-octo-dimensions="package_name:accepts"
                        style="width: 24px;" aria-label="Reveal accepts dependencies" aria-expanded="false"
                        data-sub-dependency-url="#">
                  <span class="text-gray-light text-bold mr-3">
                    <svg aria-hidden="true" class="octicon octicon-chevron-down js-expanded d-none" height="16"
                         version="1.1" viewBox="0 0 10 16">
                      <path fill-rule="evenodd" d="M5 11L0 6l1.5-1.5L5 8.25 8.5 4.5 10 6z">

                      </path>
                    </svg>
                  </span>
                </button>
                <a href="#">
                  <img alt="#" class="avatar mr-2" height="20" src="#" width="20">
                </a>
                <span class="f5 text-gray-light">
                  <a href="#" data-octo-click="dep_graph_package"> Person /
                  <span class="text-bold">update</span>
                  </a>
                </span>
                <div class="d-flex flex-auto flex-justify-end flex-items-center">
                  <code> ^ 0.0.0</code>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/insights/forks.html.erb
<%= render partial: 'layouts/repo_heading' %>
<div class="container new-discussion-timeline experiment-repo-nav">
  <div class="repository-content">
    <div class="columns">
      <div class="column one-fourth">
        <%= render partial: 'insights/menu' %>
      </div>
      <div class="column three-fourth">
        <div id="network" class="network">
          <div class="repo">
            <img alt="#" class="gravatar" height="16" src="#" width="16">
            <span class="current-repository">
              <a href="#">gitclub</a>
              /
              <a href="#">gitclub</a>
            </span>
          </div>
          <div class="repo">
            <img alt class="network-tree" src="#">
            <img alt="#" class="gravatar" height="16" src="#" width="16">
            <a href="#">andreydro</a>
            /
            <a href="#">gitclub</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/insights/network.html.erb
<%= render partial: 'layouts/repo_heading' %>
<div class="container new-discussion-timeline experiment-repo-nav">
  <div class="repository-content">
    <div class="columns">
      <div class="column one-fourth">
        <%= render partial: 'insights/menu'%>
      </div>
      <div class="column three-fourth">
        <div id="network" class="network">
          <div class="Box mb-3 position-relative overflow-hidden lh-condensed-ultra js-network-graph-container"
               data-network-graph-meta-url="#" data-network-grapg-chunk-url="#">
            <canvas width="980" height="600" style="z-index: 0; cursor: move;">
              <p>Sorry, your browser doesn't support the canvas element </p>
              <p>Please update yor browser</p>
            </canvas>
            <div class="position-absolute top-0 right-0 left-0 large-loading-area d-none">
              <img alt height="32"" src="#" width="32">
            </div>
          </div>
          <button type="button" class="btn-link keyboard-shortcuts text-small text-gray js-keyboard-shortcuts">
            Keyboard shortcuts avilable
            <svg aria-hidden="true" class="octicon octicon-keyboard" height="16" version="1.1" veiwBox="0 0 16 16" width="16">
              <path fill-rule="evenodd" d="M 10 5 H 9 V 4 h 1 v 1 Z M 3 6 H 2 v 1 h 1 V 6 Z m 5 -2 H 7 v 1 h 1 V 4 Z M 4 4 H 2
              v 1 h 2 V 4 Z m 8 7 h 2 v -1 h -2 v 1 Z M 8 7 h 1 V 6 H 8 v 1 Z m -4 3 H 2 v 1 h 2 v -1 Z m 8 -6 h -1 v 1 h 1 V
              4 Z m 2 0 h -1 v 1 h 1 V 4 Z m -2 5 h 2 V 6 h -2 v 3 Z m 4 -6 v 9 c 0 0.55 -0.45 1 -1 1 H 1 c -0.55 0 -1 -0.45
              -1 -1 V 3 c 0 -0.55 0.45 -1 1 -1 h 14 c 0.55 0 1 0.45 1 1 Z m -1 0 H 1 v 9 h 14 V 3 Z M 6 7 h 1 V 6 H 6 v 1 Z m
              0 -3 H 5 v 1 h 1 V 4 Z M 4 7 h 1 V 6 H 4 v 1 Z m 1 4 h 6 v -1 H 5 v 1 Z m 5 -4 h 1 V 6 h -1 v 1 Z M 3 8 H 2 v 1
              h 1 V 8 Z m 5 0 v 1 h 1 V 8 H 8 Z M 6 8 v 1 h 1 V 8 H 6 Z M 5 8 H 4 v 1 h 1 V 8 Z m 5 1 h 1 V 8 h -1 v 1 Z"></path>
            </svg>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/insights/traffic.html.erb
<%= render partial: 'layouts/repo_heading' %>
<div class="container new-discussion-timeline experiment-repo-nav">
  <div class="repository-content">
    <div class="columns">
      <div class="column one-fourth">
        <%= render partial: 'insights/menu' %>
      </div>
      <div class="column three-fourth">
        <div id="js-clones-graph" class="boxed-group flush">
          <h3>Git clones</h3>
          <div class="boxed-group-inner">
            <div class="graph-canvas traffic-graph uniques-graph js-graph" data-url="#" data-graph-name="traffic-clones">
              <div class="activity">
                <img class="graph-loading dots" src="#" width="64" alt>
                <div class="graph-loading msg">
                  <p>Crunching the latest data, just for you. Hang right...</p>
                </div>
                <div class="graph-empty msg mt-6">
                  <h4>We don`t have enough data to show anything useful.</h4>
                  <p>It usually takes about a week to populate this graph</p>
                </div>
                <div class="graph-no-usable-data msg mt-6">
                  <p>We need at least ine non-empty commit with an email to generate this graph.</p>
                </div>
              </div>
              <div class="graph-error flash flash-error mt-6">
                <p>We tried our best, but the graph wouldn`t load. Try reload the page.</p>
              </div>
              <svg width="719" height="243" class="vis">
                <g transform="translate(40,20)">
                </g>
              </svg>
            </div>
            <div class="traffic-graph-stats">
              <ul class="summary-stats">
                <li>
                  <span class="num js-traffic-total clones">?</span> Clones
                </li>
                <li>
                  <span class="num js-traffic-uniques uniques">?</span> Uniques cloners
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div id="js-visitors-graph" class="boxed-group flush">
          <h3>Visitors</h3>
          <div class="boxed-group-inner">
            <div class="graph-canvas traffic-graph uniques-graph js-graph" data-url="#" data-graph-name="traffic-visitors">
              <div class="activity">
                <img class="graph-loading dots" src="#" width="64" alt>
                <div class="graph-loading msg">
                  <p>Crunching the latest data, just for you. Hang tight...</p>
                </div>
                <div class="graph-empty msg mt-6">
                  <h4>We don`t have enough data to show anything useful.</h4>
                  <p>It ussaly takes about a week to populate this graph.</p>
                </div>
                <div class="graph-no-usable-data msg mt-6">
                  <p>We need at least one non-empty commit with en email to generate this graph.</p>
                </div>
              </div>
              <div class="graph-error flash flash-error mt-6">
                <p>We tried our best, but the graph wouldn`t load. Try reloading the page.</p>
              </div>
              <svg width="719" height="243" class="vis">
                <g transform="translate(40,20)"></g>
              </svg>
            </div>
            <div class="traffic-graph-stats">
              <ul class="summary-stats">
                <li>
                  <span class="num js-traffic-total visits">?</span> Views
                </li>
                <li>
                  <span class="num js-traffic-total visits">?</span> Uniques visitors
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="columns top-lists">
          <div id="top-domains" class="column one-half top-domains" data-pjax-container data-pjax>
            <div class="boxed-group">
              <h3>Referring sites</h3>
              <table class="capped-list boxed-group-inner">
                <thead>
                  <tr>
                    <th>Site</th>
                    <th class="middle">Views</th>
                    <th class="middle">Unique visitors</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td class="capped-list-label">
                      <img alt class="top-domains-icon" height="16" src="#" width="15">github.com
                    </td>
                    <td class="middle">?</td>
                    <td class="middle">?</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          <div class="column one-half top-content boxed-group">
            <h3>Popular content</h3>
            <table class="capped-list mini-icons boxed-group-inner">
              <thead>
                <tr>
                  <th>Content</th>
                  <th class="middle">Views</th>
                  <th class="middle"> Unique  visitors</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td class="capped-list-label">
                    <svg aria-hidden="true" class="octicon octicon-file" height="16" version="1.1" viewBox="0 0 12 16" width="12"></svg>
                    <a title="file n" href="#">File n</a>
                  </td>
                  <td class="middle">?</td>
                  <td class="middle">?</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>