config/routes.rb
Rails.application.routes.draw do
  root 'home_page#index'
  get '/pull_requests',    to: 'pull_requests#index'
  get '/pulse',            to: 'insights#pulse'
  get '/contributors',     to: 'insights#contributors'
  get '/community',        to: 'insights#community'
  get '/traffic',          to: 'insights#traffic'
  get '/commits',          to: 'insights#commits'
  get '/code_frequency',   to: 'insights#code_frequency'
  get '/dependency_graph', to: 'insights#dependency_graph'
  get '/network',          to: 'insights#network'
  get '/forks',            to: 'insights#forks'
  get '/signup',           to: 'users#new'
  post 'signup',           to: 'users#create'
  get '/profile',          to: 'users#profile'
  get '/login',            to: 'sessions#new'
  post '/login',           to: 'sessions#create'
  delete '/logout',        to: 'sessions#destroy'
  get '/issues',           to: 'issues#show'
  get '/edit',             to: 'users#edit'
  get '/activate',         to: 'account_activations#activate'
  get '/new',              to: 'repositories#new'
  post '/new',             to: 'repositories#create'
  get '/index',            to: 'repositories#index'
  resources :repositories
  resources :users
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/layouts/_repo_heading.html.erb
<div class="repo-heading">
  <div class="container">
    <div class="name-of-repository">
      <%= link_to current_user.name, current_user %> / <%= link_to @repository.title, @repository %>
      <button class="float-right">Fork</button>
      <button class="float-right">Star</button>
      <button class="float-right">Watch</button>
    </div>
    <ul class="repository-tabs">
      <li><%= link_to "Code", "#" %></li>
      <li><%= link_to "Issues", issues_path %></li>
      <li><%= link_to "Pull requests", pull_requests_path %></li>
      <li><%= link_to "Projects", "#" %></li>
      <li><%= link_to "Wiki", "#" %></li>
      <li><%= link_to "Insights", pulse_path %></li>
      <li><%= link_to "Settings", "#" %></li>
    </ul>
  </div>
</div>

app/views/layouts/_settings_navigation.html.erb
<div class="settings-nav">
  <div class="settings-nav-head">Personal settings</div>
  <div class="settings-nav-links"><%= link_to "Profile", "#" %></div>
  <div class="settings-nav-links"><%= link_to "Account", "#" %></div>
  <div class="settings-nav-links"><%= link_to "Emails", "#" %></div>
  <div class="settings-nav-links"><%= link_to "Notifications", "#" %></div>
  <div class="settings-nav-links"><%= link_to "Notifications", "#" %></div>
  <div class="settings-nav-links"><%= link_to "SSH and GPG keys", "#" %></div>
  <div class="settings-nav-links"><%= link_to "Security", "#" %></div>
  <div class="settings-nav-links"><%= link_to "Blocked users", "#" %></div>
  <div class="settings-nav-links"><%= link_to "Repositories", "#" %></div>
  <div class="settings-nav-links"><%= link_to "Organizations", "#" %></div>
  <div class="settings-nav-links"><%= link_to "Saved replies", "#" %></div>
  <div class="settings-nav-links"><%= link_to "Applications", "#" %></div>
  <div class="settings-nav-links" style="border: none"><%= link_to "Developer settings", "#" %></div>
</div>

app/views/layouts/_top.html.erb
<div class="top">
  <div id="central-block">
    <% if logged_in? %>
      <div class="icon"><%= link_to("", current_user) %></div>
      <form accept-charset="UTF-8" action="#" class="subnav-search float-left search-form-login" data-pjax="true" method="get">
        <div style="margin: 0; padding: 0; display: inline;">
          <input name="utf8" type="hidden" value="+">
        </div>
        <input aria-label="Search all issues" class="form-control search-form-inside" data-hotkey="/"
               name="q" placeholder="Search GitClub" type="text" value="">
      </form>
      <div class="menu-links"><%= link_to("Pull requests", "#") %></div>
      <div class="menu-links"><%= link_to("Issues", "#") %></div>
      <div class="menu-links"><%= link_to("Marketplace", "#") %></div>
      <div class="menu-links"><%= link_to("Explore", "#") %></div>
      <div class="input-or-regist">
        <ul class="account-button">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= gravatar_for @user %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu account-menu">
              <li>Signed in as <%= current_user.name %></li>
              <li class="divider"> </li>
              <li><%= link_to "Your profile", profile_path %></li>
              <li><%= link_to "Your stars", '#' %></li>
              <li><%= link_to "Your gists", '#' %></li>
              <li class="divider"> </li>
              <li><%= link_to "Help", '#' %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li><%= link_to "Sign out", logout_path, method: :delete %></li>
            </ul>
          </li>
        </ul>
      </div>
    <% else %>
      <div class="icon"><%= link_to("", root_path) %></div>
      <div class="menu-links"><%= link_to("Features", "#") %></div>
      <div class="menu-links"><%= link_to("Business", "#") %></div>
      <div class="menu-links"><%= link_to("Explore", "#") %></div>
      <div class="menu-links"><%= link_to("Marketplace", "#") %></div>
      <div class="menu-links"><%= link_to("Pricing", "#") %></div>
      <form accept-charset="UTF-8" action="#" class="subnav-search float-left search-form" data-pjax="true" method="get">
        <div style="margin: 0; padding: 0; display: inline;">
          <input name="utf8" type="hidden" value="+">
        </div>
        <input aria-label="Search all issues" class="form-control search-form-inside" data-hotkey="/"
               name="q" placeholder="Search GitClub" type="text" value="">
      </form>
      <div class="input-or-regist">
        <div class="menu-links"><%= link_to("Sing In", login_path) %></div>
        <div class="menu-links color-gray">or</div>
        <div class="menu-links"><%= link_to("Sing Up", signup_path) %></div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gitclub</title>

    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css"
          integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="icon" type="image/x-icon" href="https://assets-cdn.github.com/favicon.ico">
  </head>

  <body>
    <%= render partial: 'layouts/top' %>
    <%= render partial: 'layouts/flash' %>

    <%= yield %>
  </body>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    title Gitclub
    meta charset="utf-8"
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render 'shared/header'
    = yield